# This is a basic workflow to help you get started with Actions

name: CodeLab CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install claat@latest
        run: go install github.com/googlecodelabs/tools/claat@latest
      - name: Build html
        run: ~/go/bin/claat export -f html -o build mylab.md
      # Copy the img directory into the docs directory inside the build directory
      - name: Copy the img directory into docs directory
        run: cp -r img/ build/docs/  
      - name: Copy the build directory
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: build/

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/ # replace with the path to your build directory
