# This is a basic workflow to help you get started with Actions

name: CodeLab CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker pull bpetetot/claat,
          docker container run -it -v $(pwd):/app bpetetot/claat export -o labs mylab.md
      - name: Copy the labs directory
        uses: actions/upload-artifact@v3
        with:
          name: labs
          path: . # or path/to/artifact
